name       : python-jsonschema
version    : 4.17.3
release    : 17
source     :
    - https://github.com/python-jsonschema/jsonschema/archive/refs/tags/v4.17.3.tar.gz : d2fa5bcddc25753dbb4cbea0b5a9154116880a5c9d991a10ed460d99a66bd5b3
homepage   : https://github.com/Julian/jsonschema
license    : MIT
component  : programming.python
summary    : An implementation of JSON Schema validation for Python
description: |
    An implementation of JSON Schema validation for Python
builddeps  :
    - python-hatch-fancy-pypi-readme
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-pyrsistent      # check
    - python-pytest          # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-attrs
    - python-pyrsistent
    - python-six
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
