name       : python-jsonschema
version    : 2.5.1
release    : 1
source     :
    - https://pypi.python.org/packages/58/0d/c816f5ea5adaf1293a1d81d32e4cdfdaf8496973aa5049786d7fdb14e7e7/jsonschema-2.5.1.tar.gz : 36673ac378feed3daa5956276a829699056523d7961027911f064b52255ead41
license    : MIT
component  : programming.python
summary    : An implementation of JSON Schema validation for Python
description: An implementation of JSON Schema validation for Python
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
