name       : python-jsonschema
version    : 4.4.0
release    : 12
source     :
    - https://github.com/Julian/jsonschema/archive/refs/tags/v4.4.0.tar.gz : b32c22ba26c67227699085c933d53a3c868937e6f5baa642f886d0d6b1f3aaf3
homepage   : https://github.com/Julian/jsonschema
license    : MIT
component  : programming.python
summary    : An implementation of JSON Schema validation for Python
description: |
    An implementation of JSON Schema validation for Python
builddeps  :
    - python-pyrsistent      # check
    - python-build
    - python-installer
    - python-pytest          # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-attrs
    - python-pyrsistent
    - python-six
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
