name       : python-jsonschema
version    : 3.2.0
release    : 9
source     :
    - https://pypi.python.org/packages/source/j/jsonschema/jsonschema-3.2.0.tar.gz : c8a85b28d377cc7737e46e2d9f2b4f44ee3c0e1deac6bf46ddefc7187d30797a
homepage   : https://github.com/Julian/jsonschema
license    : MIT
component  : programming.python
summary    : An implementation of JSON Schema validation for Python
description: |
    An implementation of JSON Schema validation for Python
builddeps  :
    - pkgconfig(python3)
    - python-importlib-metadata
    - python-pyrsistent
    - python-pytest
    - python-setuptools-scm
    - python-twisted
    - python-vcversioner
rundeps    :
    - python-attrs
    - python-importlib-metadata
    - python-pyrsistent
    - python-six
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
