name       : python-jsonschema
version    : 2.6.0
release    : 3
source     :
    - https://pypi.python.org/packages/58/b9/171dbb07e18c6346090a37f03c7e74410a1a56123f847efed59af260a298/jsonschema-2.6.0.tar.gz : 6ff5f3180870836cae40f06fa10419f557208175f13ad7bc26caa77beb1f6e02
license    : MIT
component  : programming.python
summary    : An implementation of JSON Schema validation for Python
description: |
    An implementation of JSON Schema validation for Python
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - python-vcversioner
rundeps    :
    - python-functools32
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
