name       : python-jsonschema
version    : 4.8.0
release    : 15
source     :
    - https://github.com/python-jsonschema/jsonschema/archive/refs/tags/v4.8.0.tar.gz : 47da32bc7a017df825b2a92c7ada2ad327489bb315cbfbb9cd68fd8c7f6671e5
homepage   : https://github.com/Julian/jsonschema
license    : MIT
component  : programming.python
summary    : An implementation of JSON Schema validation for Python
description: |
    An implementation of JSON Schema validation for Python
builddeps  :
    - python-pyrsistent      # check
    - python-build
    - python-hatch-vcs
    - python-installer
    - python-pytest          # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-attrs
    - python-pyrsistent
    - python-six
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
