name       : python-jsonschema
version    : 4.5.1
release    : 14
source     :
    - https://github.com/Julian/jsonschema/archive/refs/tags/v4.5.1.tar.gz : ff315a177cb94d65c642e3e41fb122193ef6611fba7cc155c688662bd9821ff4
homepage   : https://github.com/Julian/jsonschema
license    : MIT
component  : programming.python
summary    : An implementation of JSON Schema validation for Python
description: |
    An implementation of JSON Schema validation for Python
builddeps  :
    - python-pyrsistent      # check
    - python-build
    - python-installer
    - python-pytest          # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-attrs
    - python-pyrsistent
    - python-six
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
